run_logged $OMAKUB_INSTALL/packaging/base.sh
run_logged $OMAKUB_INSTALL/packaging/flathub.sh
run_logged $OMAKUB_INSTALL/packaging/remove-snap.sh
run_logged $OMAKUB_INSTALL/packaging/pipx.sh
run_logged $OMAKUB_INSTALL/packaging/fonts.sh
run_logged $OMAKUB_INSTALL/packaging/nvim.sh
run_logged $OMAKUB_INSTALL/packaging/docker.sh
run_logged $OMAKUB_INSTALL/packaging/mise.sh
run_logged $OMAKUB_INSTALL/packaging/icons.sh
run_logged $OMAKUB_INSTALL/packaging/chromium.sh
run_logged $OMAKUB_INSTALL/packaging/webapps.sh
run_logged $OMAKUB_INSTALL/packaging/tuis.sh
run_logged $OMAKUB_INSTALL/packaging/npm.sh
